# Generated by Django 3.2.6 on 2021-11-26 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211125_0926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'cities'},
        ),
        migrations.RenameField(
            model_name='city',
            old_name='city_name',
            new_name='name',
        ),
    ]
